# Site settings
title: Joop Laan
email: joop@kiux.nl
description:  Web developer & general communication enthusiastic
# the subpath of your site, e.g. /blog/
baseurl:
# The base hostname & protocol for your site without slash.
url:  http://www.jooplaan.com
twitter_username: j00p
github_username:  jooplaan

atom_path : /atom.xml
rss_path : /rss.xml

# Build settings
markdown: kramdown

highlighter: pygments

gems:         [
                'jekyll-sitemap',
                'jekyll-paginate'
              ]

# Pagination settings
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
  blog:
    output: true
    permalink: /blog/:path/


